# Generated by Django 4.1.1 on 2022-10-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0002_ratings_negative_ratings_neutral_ratings_positive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratings",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
