# Generated by Django 4.1.2 on 2022-10-20 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0003_ratings_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratings",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="ratings",
            constraint=models.UniqueConstraint(
                fields=("name", "date"), name="unique_name_date_combination"
            ),
        ),
    ]
